name: "Release please"

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write

jobs:
    main:
        name: "Release please"
        runs-on: ubuntu-latest
        steps:
            - name: Create release
              uses: googleapis/release-please-action@v4
              with:
                  release-type: "node"
                  token: ${{ secrets.GITHUB_TOKEN }}
